### ISSUE TITLE
Repeated Header and footer count

### ISSUE THREAD

**Issue by rajcitystar** [OfficeDev/Open-Xml-PowerTools#11]
Acutally i need to get the characters count in docx(including header and footer).
but open xml sdk is not giving header and footer part count.
now i have read the header and footer text. but I would like to know the number of time the header and footer text used in docx. so that i can multiply and get the correct count of header and footer text

**Comment by EricWhiteDev** [comment]
@rajcitystar The issue of getting the correct character count including headers and footers is pretty complicated, in that for any section, the headers and footers may be 'inherited' from the previous section.  The semantics of the markup are a bit complicated, in that the lack of one of the three possible w:headerReference elements in a w:sectPr can mean that there is, for instance, only a default header (not separate headers for even and odd pages).  It can also mean that the header reference is 'inherited' from the previous section.

But this is the more simple issue.  The more complicated issue is determining pagination, so that you could know how many pages there are in a document, and which content is on which page, so that you could properly count the headers / footers as appropriate.  There is no pagination facility in the Open-Xml-Sdk, nor in Open-Xml-PowerTools.  This is a project that currently is not on the schedule.  We have discussed putting this on the schedule, but it is not contemplated for the near future.

If you really want to get a good count, then currently, I believe that automating Word itself is the best solution.  I have never implemented this type of functionality in Word automation, so am unclear on the best approach for this.

I wish I had a better answer for you, but unfortunately I don't.

I am closing this issue, because it is out of scope for Open-Xml-PowerTools, at least for now.
