### ISSUE TITLE
Do transformations in footer rows, so that can pull data into them.

### ISSUE THREAD

**Issue by EricWhiteDev** [OfficeDev/Open-Xml-PowerTools#23]
@BrettBailey suggested this.

**Comment by EricWhiteDev** [comment]
Fixed

https://github.com/OfficeDev/Open-Xml-PowerTools/commit/cdd270f21b36ca5e9052b3b8b3d3fe6139ba9b0e

**Comment by BrettBailey** [comment]
Thanks for adding that Eric I really appreciate it.

**Comment by EricWhiteDev** [comment]
Did you give it a try?  Look at test DA236-Table-With-Sum

**Comment by BrettBailey** [comment]
Hi Eric

Sorry for not getting back to you I've been away on holiday myself.  I have tried it out today and it works a treat :-)  I really like that you can leave blank rows and then have the transforms on the very last row.

I've have had a little monkey about with the code and I have it so that you can use this in the footer:

<Content Select="sum(./Orders//Quantity/text())"/>

which sums up on the fly with xPath will be really useful for us and other users I think.  I'll send you a pull request
