### ISSUE TITLE
DocumentAssembler: Repeat-Element doesn't find matching EndRepeat

### ISSUE THREAD

**Issue by chrlutz** [OfficeDev/Open-Xml-PowerTools#30]
I had an "In-Paragraph Repitition" like

&lt;Repeat Select="./car"/>&lt;Content Select="@name" />, &lt;EndRepeat />

and i splitted it up into a multiple paragraph-version (by pressing enter after at the end of the content controls). Now it looks like this:

  &lt;Repeat Select="./car"/>
  &lt;Content Select="@name" />
  &lt;EndRepeat />

now, for some reason, DocumentAssembler doesn't find the corresponding &lt;EndRepeat /> element, even if the logic is correct from my point of view. 

I wanted to attach the docx-file, but it was denied. So here's the screenshot.
![matchingendrepeatnotfound](https://cloud.githubusercontent.com/assets/10079489/10938600/dbd332ae-82fb-11e5-8348-d03911e5aa12.png)

I already figured out that this situation could be "repaired" by inserting the content controls for Repeat and EndRepeat again. After doing so, I got the following elements:
![matchingendrepeatnotfound2](https://cloud.githubusercontent.com/assets/10079489/10938699/79dd31c0-82fc-11e5-9f83-9cbbfe851b8c.png)

Please note that optical the first and the second picture differ. In the second picuture there are small &lt;&lt; and >> symbols in the blue content control markers. I guess they show if the content controll represents a complete paragraph!?

From point of view, both versions are logically the same and should behave equally. 

This issue is one of the biggest pitfalls for template creators. I already stumbled over it many times. The worse thing with this issue is, that it seems to be closely related to #29 ,because the error is not reported as expected, but an invalid DOCX is created.

This is because in this case I (again) got the following invalid XML-result:

    <w:p w:rsidRDefault='00F26444' w:rsidR='00F26444' w:rsidP='008C221B'>
      <w:p>
        <w:r>
          <w:rPr>
            <w:color w:val='FF0000' />
            <w:highlight w:val='yellow' />
          </w:rPr>
          <w:t>Repeat does not have matching EndRepeat</w:t>
        </w:r>
      </w:p>
    </w:p>

(see the w:p in w:p)

**Comment by EricWhiteDev** [comment]
The issue here is that Repeat and EndRepeat (also Conditional / EndConditional) should work at the run level or block level.  The problem occurs when the Repeat and EndRepeat are at the run level, in different paragraphs.  I changed it as follows:

- if there is a run level Repeat / EndRepeat, and that is the only metadata in a paragraph, I move it to the block level.  This fixes your situation.  Both the Repeat / EndRepeat are moved to block level, and then they find a match.  This also fixes the case where the Repeat is at the run level, and the EndRepeat is at the block level - the Repeat is moved to block level, and then it can be matched to the EndRepeat.
- if the Repeat / EndRepeat are at the run level, and in the same paragraph, this is fine.
- The Table metadata should always be at the block level, so if it is at the run level, it is moved to the block level.

If there is a Repeat / EndRepeat at the run level, and it is not a matching pair, then this is an error.  In other words, you can't start a Repeat at the run level, with content before the Repeat, and the EndRepeat is at the block level further on in the document.

It seemed to me that it is useful to have a NotMatch attribute for Conditional, so I added that.  This enables the scenario where you have two alternative pieces of content, only one of which should be added at the run level (or block level).

Added appropriate test cases for all of these situations.
