### ISSUE TITLE
HTML Converter : Support Images

### ISSUE THREAD

**Issue by BrettBailey** [OfficeDev/Open-Xml-PowerTools#41]
The docx to Html Converter seems to ignore images.

**Comment by EricWhiteDev** [comment]
It does support images.  When you run the WmlToHtmlConverter example, you should see some documents that contain images that get converted and put into the HTML.

I am wondering if your event handler for handling images, which you must pass to WmlToHtmlConverter, isn't quite correct.

BTW, note that I recently renamed HtmlConverter.cs (and class) to WmlToHtmlConverter.cs.  For back compat, I added a wrapper class, HtmlConverter, which has the identical API as it used to have.  However, better to use the WmlToHtmlConverter class instead of HtmlConverter.

**Comment by BrettBailey** [comment]
Yes, you're right, there is a problem with the event handler.

**Comment by EricWhiteDev** [comment]
Ok, closing this issue then.
