### ISSUE TITLE
using DocumentAssembler, word template tags

### ISSUE THREAD

**Issue by arisco** [OfficeDev/Open-Xml-PowerTools#45]
Hi Eric,
thanks for DocumentAssembler introduction video is very usefull.

But how could I define a image content in my .docx template?
For regular text content is, for example:  "<Content select = "./Name"/>
For Table is "<Table Select="./Devices/Device"/>
there are Repeat and Conditional tags too.

And for image? is something like media?

Where could I find all avaliable tags?

I have search in OpenXmlPowerToolsExamples project without success

those tags are specific of Open-Xml-PowerTools or are from XPath or are from Word..... I'm confused

thanks for your time.

**Comment by EricWhiteDev** [comment]
Hi,

Certainly images and media need to be added to DocumentAssembler.  I plan on adding images this month, but we'll see.  Currently, I'm working on the functionality to include a named range from Excel, or any specified sheet/range from Excel into the generated document.

Also, you are correct, there needs to be better documentation.  The two videos actually demonstrate everything that is possible, at this point in time, with the exceptions of some small enhancements that we've made since then.  You can see evidence of these enhancements in the commit history.

All of the tags that you see, i.e. Content, Repeat, EndRepeat, Conditional, EndConditional, Table, are specific to Open-Xml-PowerTools and DocumentAssembler.  Once you generate the finished document, none of this is left in the file.  The result is a canonical Open XML document.

I'm leaving this issue open - once I add images, and create a doc page for DocumentAssembler, I'll close the issue.

Cheers, Eric

**Comment by Will-Gregg** [comment]
Issue has dependency on #42

**Comment by luizfbicalho** [comment]
Any news on this issue?

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
