### ISSUE TITLE
HtmlToWml - span tag generates new paragraph

### ISSUE THREAD

**Issue by k59319** [OfficeDev/Open-Xml-PowerTools#47]
If I use 'span' tag in my HTML code, the converter creates a new paragraph on each 'span' instead of just changing a text style inside a paragraph.

Example: my HTML code looks like
````html
test <span style="text-decoration:line-through;">text</span> paragraph
````
It generates one line of text in a web browser:
test ~~text~~ paragraph

But HtmlToWml converter generates ***three lines*** of text like this:
test
~~text~~
paragraph

How to make text decoration changes inside a paragraph?

[input.txt](https://github.com/OfficeDev/Open-Xml-PowerTools/files/58293/input.txt)
[input_css.txt](https://github.com/OfficeDev/Open-Xml-PowerTools/files/58297/input_css.txt)
[example_output.docx](https://github.com/OfficeDev/Open-Xml-PowerTools/files/58298/example_output.docx)

**Comment by EricWhiteDev** [comment]
The problem is that HtmlToWmlConverter interprets those spans as at the block level, not the run level.  If you enclose the text in a paragraph (or a div), then the spans will result in text decoration changes inside a paragraph.

There probably needs to be some changes to that algorithm.  It is probably more simplistic than it could be.  In the extreme case, HTML can look like this:

    <span>text</span>
    <div><div><span><span>text</span></span></div></div>

The algorithm to determine where paragraphs should be created, and where runs should be created is pretty complex.

But in your case, it is pretty simple.  Just put in a <p> or <div> and it should work fine for you.

**Comment by k59319** [comment]
Actually I have this text inside a 'td' tag. I can make a preprocessor that will put content of 'td' tag into a div.
````html
<td class="ms-rteTableFooterOddCol-default" rowspan="1" colspan="1">​1ggggg<span style="color: rgb(236, 0, 140); text-decoration: line-through; background-color: rgb(208, 255, 188);">​aaaaaa</span></td>
````
