### ISSUE TITLE
Generate appropriate error when Conditional content control is placed at the run-level instead of block-level

### ISSUE THREAD

**Issue by EricWhiteDev** [OfficeDev/Open-Xml-PowerTools#55]
Also need to examine other content controls that should be at the block-level, appropriately handle.

**Comment by PeteBritton68** [comment]
Hi Eric,

Does this mean that you can't have a conditional select at run-level?

Thanks,
Pete

**Comment by EricWhiteDev** [comment]
You are right, conditional should also be able to be at the run level.  But if it is at the run level, the end conditional should be in the same paragraph, at least I think it is reasonable that it should be.  But currently if there is a conditional at the run level in one paragraph, and the end conditional is in another paragraph, not sure if that works.

**Comment by PeteBritton68** [comment]
Hi Eric,

Thanks for your quick reply. You got me thinking - you seemed to pretty confident that a conditional select within a paragraph worked so I was wondering why it didn't, even in a very simple example. So I tried the same simple example using content controls instead of the <# ... #> syntax and lo and behold, it worked!

So, my simple template is (with the first paragraph using content controls):

I am male. <Conditional Select="LivingWithPartner" Match="true" />I am living with my <Content Select="PartnerRelationship" />.<EndConditional />

I am male. <# <Conditional Select="LivingWithPartner" Match="true" /> #>I am living with my <# <Content Select="PartnerRelationship" /> #>.<# <EndConditional /> #>

which produces the following document:

I am male. I am living with my wife.

I am male. I am living with my .e2becd12-73fd-4473-b63b-827a5f148fd4

As you can see, the version not using the content controls doesn't work. I am now converting my template to use content controls instead of the <# ... #> syntax to get it to work correctly but it would be good if it could be made to work in both cases.

Regards,
Pete

**Comment by tomjebo** [comment]
Closing all issues as this repo is being archived and will no longer be maintained by Microsoft. The project is licensed for continued use and development by forking to your own repo.
