### ISSUE TITLE
Merge Document Issue (Urgent Please)

### ISSUE THREAD

**Issue by Ganesan-Chandran** [OfficeDev/Open-Xml-PowerTools#8]
Hi,

I have use latest Document builder version.But still i got document merge issue.

![image2 1](https://cloud.githubusercontent.com/assets/14222592/9813829/8da9ffd8-58a6-11e5-9074-455b0726dc93.png)

The content of second word templates is merge with content of previous word template.I need the second word template start with as new page.
How to resolve above problem.
(Any code is there or any word setting is needed)

**Comment by EricWhiteDev** [comment]
Can you please attach some sample documents, along with the code that you are using with DocumentBuilder, so that I can see the issue exactly?  I believe that the keepSections option that you can use with each source in DocumentBuilder will solve your problem, but I am not fully clear on the exact issue you face, so need the sample documents.

**Comment by EricWhiteDev** [comment]
Closing this issue until we have documents that repro.
